### ISSUE TITLE
Add GPU support to MED-condaenv

### ISSUE THREAD

**Issue by max-anu** [ACCESS-NRI/ACCESS-Vis#11]
The current [med-condaenv](https://github.com/ACCESS-NRI/MED-condaenv) uses lavavu-osmesa (a cpu only version of lavavu).

This can be changed to use a GPU by updating the conda environment.yml to remove removing lavavu-osmesa and adding:
`dependencies:
  - moderngl[headless]
  - pip:
    - lavavu`

We should have two environments - CPU and GPU.

**Comment by max-anu** [comment]
@rbeucher Did we want to change the default to GPU?

**Comment by rbeucher** [comment]
We probably need a GPU and a CPU version.

**Comment by rbeucher** [comment]
Are you sure that it is what is going on here.
We don't have `moderngl` install for sure but I have installed `lavavu` not `lavavu-osmesa`
