### ISSUE TITLE
Add a method to reset light controls to default values

### ISSUE THREAD

**Issue by max-anu** [ACCESS-NRI/ACCESS-Vis#14]
Currently there is no way (at least that I know of) to reset the properties to their default values.
e.g. lv.set_properties(diffuse=0.8, ambient=0.1, specular=0.35, shininess=0.03)
The same is true for lv.brightness_contrast_saturation(0.5, 0.7, 0.2)

**Comment by rbeucher** [comment]
@OKaluza any comments on this?
I am not sure we need the option to reset the orientation. This can be saved in a Python variable @max-anu

**Comment by OKaluza** [comment]
If you want to restore a property to the default you can pass None as the value
eg: `lv['brightness'] = None`
It might be worth changing the convenience function lv.brightness_contrast_saturation to support resetting defaults via passing no args, I'll have a look at that.
You can also save and restore the full state of all global/object properties easily with `lv.save('state.json')` and `lv.file('state.json')` to load.

**Comment by OKaluza** [comment]
Actually, lv.brightness_contrast_saturation() with no args already sets the default values

**Comment by max-anu** [comment]
lv.save() and lv.file() addresses what i thought was a missing feature. I'll add this into one of the recipes.
