### ISSUE TITLE
Interactive viewer does not keep sun position.

### ISSUE THREAD

**Issue by max-anu** [ACCESS-NRI/ACCESS-Vis#15]
When using the interactive window, if the sun is set at a given time and the earth is rotated. the sun does not also rotate. I.e. if it is sunny on one side of the earth, and the earth is rotated, the opposite side will then be sunny too.

```lv = accessvis.plot_earth(waves=True, when=dt, blendtex=True, vertical_exaggeration=15, sunlight=True)
lv.set_properties(lightpos=accessvis.sun_light())
lv.window((600,600))```

**Comment by rbeucher** [comment]
@OKaluza

**Comment by OKaluza** [comment]
This is expected, sun_light() with no args returns a relative sun light which stays with the camera, the args allow providing a datetime or hour/minute etc for a fixed sun position.

It is explained in the sun_light docstring and in more detail in this notebook under ''More on lighting adjustments":
https://github.com/ACCESS-NRI/ACCESS-Visualisation-Recipes/blob/main/03-Blue-Marble-Earth-Model-from-Satellite-Data.ipynb

**Comment by max-anu** [comment]
It works correctly. I thought sun_light() did current time, but you need to pass now=True as an argument.
