### ISSUE TITLE
Additional frames required or end of videos are cut off

### ISSUE THREAD

**Issue by OKaluza** [ACCESS-NRI/ACCESS-Vis#18]
There is a problem in the LavaVu video encoder that requires writing the additional frames at the end of the video or the last few seconds are cut off, I think this has been fixed in https://github.com/lavavu/LavaVu/commit/c7c4df6b6042a3d062397c708526ebc0d0dcf2d2 but needs to be tested and confirmed with the ACCESS-Vis example notebooks.
If it is fixed, the final loop in the video encoding examples that write 30 extra frames can be removed

**Comment by rbeucher** [comment]
Have you updated the code on Pypi / conda?

**Comment by OKaluza** [comment]
It's fixed but not yet released, I'll do a LavaVu release now

**Comment by rbeucher** [comment]
Thanks. Let me know

**Comment by OKaluza** [comment]
This is confirmed fixed already but the other video player url issue took up all my time, it is in the latest release now.
